// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// freq_generator //
// -------------- //

#define freq_generator_wrap_target 0
#define freq_generator_wrap 12
#define freq_generator_pio_version 0

static const uint16_t freq_generator_program_instructions[] = {
            //     .wrap_target
    0xe081, //  0: set    pindirs, 1
    0x80a0, //  1: pull   block
    0x602a, //  2: out    x, 10
    0xe001, //  3: set    pins, 1
    0xe058, //  4: set    y, 24
    0xa842, //  5: nop                           [8]
    0x0085, //  6: jmp    y--, 5
    0xe000, //  7: set    pins, 0
    0xa047, //  8: mov    y, osr
    0x0089, //  9: jmp    y--, 9
    0x0043, // 10: jmp    x--, 3
    0xa042, // 11: nop
    0x0001, // 12: jmp    1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program freq_generator_program = {
    .instructions = freq_generator_program_instructions,
    .length = 13,
    .origin = -1,
    .pio_version = freq_generator_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config freq_generator_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + freq_generator_wrap_target, offset + freq_generator_wrap);
    return c;
}
#endif

