// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// freq_generator //
// -------------- //

#define freq_generator_wrap_target 0
#define freq_generator_wrap 12
#define freq_generator_pio_version 0

static const uint16_t freq_generator_program_instructions[] = {
            //     .wrap_target
    0xe081, //  0: set    pindirs, 1
    0x80a0, //  1: pull   block
    0x602a, //  2: out    x, 10
    0x0045, //  3: jmp    x--, 5
    0x0001, //  4: jmp    1
    0xe001, //  5: set    pins, 1
    0xe058, //  6: set    y, 24
    0xa842, //  7: nop                           [8]
    0x0087, //  8: jmp    y--, 7
    0xe000, //  9: set    pins, 0
    0xa047, // 10: mov    y, osr
    0x008b, // 11: jmp    y--, 11
    0x0003, // 12: jmp    3
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program freq_generator_program = {
    .instructions = freq_generator_program_instructions,
    .length = 13,
    .origin = -1,
    .pio_version = freq_generator_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config freq_generator_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + freq_generator_wrap_target, offset + freq_generator_wrap);
    return c;
}
#endif

